### ISSUE TITLE
Drift over time

### ISSUE THREAD

**Issue by reza1376** [har-in-air/Kalmanfilter_altimeter_vario#3]
Hi 
I have tested your code , it has good precision in difference of altitude but absolute altitude is drift because of barometer . Is there any way fix this without GPS?

**Comment by har-in-air** [comment]
No one expects barometric pressure altitude to be fixed, because sea level pressure depends on the weather and location on earth (latitude).
Even if it is a stable day, you can see the altitude change by  20m over the course of the day. It can easily change by  > 100m  in a couple of hours if there is a weather front approaching.
Commercial pilots use pressure altitude also known as airspace altitude, where their altimeter assumes sea level pressure is 101325pa, because they need to maintain vertical separation from other planes, the absolute altitude is not important.
If they all calibrated their barometric pressure altimeters to their local airport, and used that for vertical separation, it would be very dangerous.

    On Thursday, 18 June, 2020, 06:18:03 pm IST, reza1376 <notifications@github.com> wrote:  
 
 


Hi
I have tested your code , it has good precision in difference of altitude but absolute altitude is drift because of barometer . Is there any way fix this?
